#!/bin/bash

# database
source <(curl https://raw.githubusercontent.com/sacrhamza/one/database/database.sh 2> /dev/null)

source ./desktop.sh
source ./download.sh
source ./remove.sh
source ./man.sh
source ./help.sh
source ./search.sh
source ./setup.sh
source ./version.sh

TRUE=1
FALSE=0

RED="\e[31m"
GREEN="\e[32m"
BLUE="\e[36m"
RESET="\e[00m"
RED_BOLD="\e[31;01m"
GREEN_BOLD="\e[32;01m"
BLUE_BOLD="\e[36;01m"

CWD="${HOME}/.local"

TEMP_DIR="/tmp"

DESKTOP_FILE_DIR="${HOME}/.local/share/applications"

ICON_DIR="${HOME}/.local/share/icons"

BIN_DIR="${HOME}/.local/bin"

ONE_DIR=$(dirname "$0")

PROGRAM_VERSION="v0.0.6"


check_package()
{
	if [[ -n "${APP_URL[$1]}" ]]
	then
		echo $TRUE
	else
		echo $FALSE
	fi 
}

#this function is used to display an error message because an option is not valid
display_error_message()
{
	local NOT_VALID_OPTION=1
	local option="${1}"
	printf "${RED_BOLD}error: ${RESET} ${BLUE_BOLD}${option}${RESET} ${RED}is not a valid option${RESET}\n"
	display_help_message
	exit $NOT_VALID_OPTION
}

#this function is used to return the action the i will use in the program to determine the valid options(install / remove)
return_action()
{
	local option="${1}"
	case "${option}" in
		install | '--install' | '-i')
			echo download
		;;
		remove | '--remove' | '-r')
			echo delete
		;;
		search | '--search' | '-s')
			echo search
		;;
		*)
		;;
	esac
	
}

ERROR=1

#this is all valid arguments that oneperson package tool can get from the user
declare -a valid_arguments
valid_arguments[0]='install --install -i --remove -r remove search --search -s'
valid_arguments[1]='list --list -l --help -h help -G --graphical graphical --all all -a init --init -I --version -v version'

#this function checks if a string is in the first or second list of valid arguments and return which one (1 / 2)
check_valid_arguments()
{
	local i
	for i in ${valid_arguments[$1]}
	do
		if [[ $2 == $i ]]
		then
			echo 1
		fi	
	done
}


zenity_app()
{
		declare -a installed_app removed_app
		declare -i remove_count=0 install_count=0
		count=0
		for i in ${!APP_URL[@]}
		do
			if [[ -d "${CWD}/$i" ]]
			then
				installed_app[${install_count}]="FALSE $i REMOVE"
				((install_count++))
			else
				removed_app[${remove_count}]="FALSE $i INSTALL"
				((remove_count++))
			fi
		done
		option=$(zenity --window-icon=${ICON_DIR}/oneperson.png --title="one" --width=750 --height=500 --list\
		--checklist \
		--column "Checkbox"  \
		--column "app" \
		--column "INSTALLE/REMOVE" ${installed_app[@]} ${removed_app[@]})
		if [[ -z "${option}" ]]
		then
			#zenity --warning --text="you should choose an app"
			exit 1
		fi
		apps=($(echo ${option} | tr '|' ' '))
		for i in ${apps[@]}
		do
			handle_action $i
		done
}

handle_action()
{
	if [[ -d "${CWD}/$1" ]]
	then
		remove_package $1 -y
	else
		download $1
	fi
}


handle_path()
{
	local paths=($(echo $PATH | tr ':' ' '))
	local found=0
	for path in ${paths[@]}
	do
		if [[ ${path} == "${BIN_DIR}" ]]
		then
			found=1
			echo 0
		fi
	done
	if [[ $found -eq 0 ]]
	then
		printf '\nPATH="${PATH}:${HOME}/.local/bin"' >> ~/.zshrc
	fi
	echo 1
}

create_if_not_found()
{
	if [[ ! -d "$1" ]]
	then
		mkdir -p "$1"
	fi
}

create_oneperson_desktop_file()
{
	if [[ ! -f "${ICON_DIR}/oneperson.png" || ! -f "${DESKTOP_FILE_DIR}/oneperson.desktop" ]]
	then
		#git clone https://github.com/sacrhamza/oneperson-icon.git /tmp/one
		cp "${ONE_DIR}/oneperson.png"  "${ICON_DIR}"
		#rm -rf /tmp/one
		printf "[Desktop Entry]
Name=One
Comment=Oneperson package tool
Exec=${BIN_DIR}/one -G
Terminal=false
Icon=oneperson
Type=Application
" > "${DESKTOP_FILE_DIR}/oneperson.desktop"
	chmod +x "${DESKTOP_FILE_DIR}/oneperson.desktop" 
	echo 1;
	fi
	echo 0;
}

setup()
{
	local variable
	create_if_not_found "${BIN_DIR}"
	create_if_not_found "${ICON_DIR}"
	if [[ ! -e "${BIN_DIR}/one" ]]
	then
		variable=1
		cp "$1" "${BIN_DIR}/one"
		chmod +x "${BIN_DIR}/one"
	fi
	let variable+=$(handle_path)
	let variable+=$(create_man_page)
	let variable+=$(create_oneperson_desktop_file)
	if [[ $variable -eq 0 ]]
	then
		printf "\n${GREEN}everything up to date${RESET}\n"
	elif [[ $(tput cols) -ge 87 ]]
	then
		printf "${GREEN}"
		while read line
		do
			printf "$line\n"
			sleep 0.009
		done < "${ONE_DIR}/art.txt"
		printf "$RESET"
	fi
}

remove_self()
{
	remove_file "$BIN_DIR/one"
	remove_file "$DESKTOP_FILE_DIR/oneperson.desktop"
	remove_file "$ICON_DIR/oneperson.png"
	remove_file "${HOME}/.local/share/man/man1/one.1"
}

take_action()
{
	local action="${1}"
	if [[ "$action" == 'all' ]]
		then
			for i in ${!APP_URL[@]}
			do
				printf "$i\n"
			done
		elif [[ "${action}" == 'list' ]]
		then
			printf "${GREEN}"
			for i in $(ls "${CWD}/")
			do
				if [[ -n "${APP_URL[${i}]}" && -d "${CWD}/${i}" ]]
				then
					printf "${GREEN_BOLD}%-15s${RESET}${DESCRIPTION[$i]}\n" "${i^}:"
				fi
			done
			printf "${RESET}"
		elif [[ "${action}" == 'graphic' ]]
		then
			zenity_app
		elif [[ "${action}" == 'init' ]]
		then
			setup $2
			exit 0
		elif [[ "${action}" == 'version' ]]
		then
			get_version
			exit 0
		elif [[ "${action}" == 'update' ]]
		then
			update
		else
			display_help_message
		fi
}


#this function is used to return one of these actions (list all help) if one of these is got (install[] remove[]) it will display the help message
return_friendly_action()
{
	local option="${1}"
	if [[ $(check_valid_arguments 0 ${option}) ]]
	then
		printf "${RED}error:${RESET} the option $i is used witout any package name\n"
		display_help_message
		return $ERROR
	fi
	case "${option}" in
		list | '--list' | '-l')
			echo list
		;;
		all | '--all' | '-a')
			echo all
		;;
		graphic | '--graphic' | '-G')
			echo graphic
		;;
		init | '--init' | '-I')
			echo init
		;;
		version | '--version' | '-v')
			echo version
		;;
		update | '--update' | '-U')
			echo update
		;;
		help | '--help' | '-h')
			display_help_message
			return 2
		;;
		*)
		;;
	esac
	return 0
}

#command line argments
package_arguments=("$@")
declare -a valid_packages

declare -i counter=0
for package in "${package_arguments[@]}"
do
	if [[ $counter -eq 0 ]]
	then
		if [[ $# -gt 1 ]]
		then
			if [[ $(check_valid_arguments 1 ${package}) ]]
			then
				printf "${RED}error: ${BLUE} option ${package}${RESET} is used with a package_name?\n"
				display_help_message
				exit $ERROR
			fi
			action=$(return_action "${package}")
			if [[ -z $action ]]
			then
				display_error_message "${package}"
			fi	
		else
			action=$(return_friendly_action "${package}")
			if [[ $? -eq $ERROR ]]
			then
				printf "${RED}error: ${BLUE}${package}${RESET} is used witout package name\n"
				display_help_message
				exit $ERROR
			elif [[ $? -eq 2 ]]
			then
				exit 0
			fi
			if [[ -z $action ]]
			then
				printf "${RED}error: ${RESET}${BLUE}${package}${RESET} no such option\n"
				display_help_message
				exit $ERROR
			fi
			if [[ "$action" == init ]]
			then
				take_action $action $0
			fi
			take_action "$action"
		fi
		((counter++))
		continue
	fi
	((counter++))
	if [[ $(check_package "${package,,}") -eq 0 && $action != search ]]
	then
		printf "${RED_BOLD}error:${RESET} ${BLUE_BOLD}${package}${RESET}${RED} is not found\n${RESET}"	
		exit $ERROR
	else
		valid_packages[$counter - 1]="${package,,}"
	fi
done

#if the counter is 0 that means that there is any command line argument so this will display help message
if [[ $counter -eq 0 ]]
then
	display_help_message
	exit 0
fi

#iterate valid packages and installing them
for i in ${valid_packages[@]}
do
	if [[ "$action" == 'download' ]]
	then
		download "$i"	
		# zenity --notification --window-icon="info" --text="$i is installed" --title="one"
	elif [[ "$action" == 'delete' ]]
	then
		remove_package "$i"
	elif [[ "$action" == 'search' ]]
	then
		search_package "$i"
	fi
done
